waiting, arrived = 0, 0
packages = [{'info_date': '',
                'notice': '',
                'pkg_name': 'Large 830 breadboards x 2',
                'shipped_ago': 14,
                'track_no': 'UN039457012CN'},
            {'info_date': '',
                'notice': '',
                'pkg_name': '5 Colors mini breadboards',
                'shipped_ago': 14,
                'track_no': 'UN036339714CN'},
            {'info_date': '',
                'notice': '',
                'pkg_name': 'Mini breadboards x 2',
                'shipped_ago': 15,
                'track_no': 'LP00105168891208'},
            {'info_date': '',
                'notice': '',
                'pkg_name': 'Bandana',
                'shipped_ago': 24,
                'track_no': 'UC999996946CN'},
            {'info_date': '',
                'notice': '',
                'pkg_name': '10Pcs 4 channel IIC I2C LLC',
                'shipped_ago': 26,
                'track_no': 'UC994073043CN'},
            {'info_date': '',
                'notice': '',
                'pkg_name': 'Axis Gyro and Accelerometer Module',
                'shipped_ago': 27,
                'track_no': 'UC988205712CN'},
            {'info_date': '',
                'notice': '',
                'pkg_name': 'DS3231 AT24C32 IIC Module Precision Clock Module',
                'shipped_ago': 28,
                'track_no': 'UC987371112CN'}]
