"""empty message

Revision ID: 333585b7e4ef
Revises: c2627b5abb77
Create Date: 2018-10-26 22:52:07.203745

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '333585b7e4ef'
down_revision = 'c2627b5abb77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('email', sa.String(length=64), nullable=False))
    op.drop_column('user', 'first_name')
    op.drop_column('user', 'last_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('last_name', sa.VARCHAR(length=64), autoincrement=False, nullable=False))
    op.add_column('user', sa.Column('first_name', sa.VARCHAR(length=64), autoincrement=False, nullable=False))
    op.drop_column('user', 'email')
    # ### end Alembic commands ###
